import { launch } from "./lib.mjs";
const results = [];
const check = (n, ok, x = "") => { results.push(ok); console.log((ok ? "PASS " : "FAIL ") + n + (x ? "  [" + x + "]" : "")); };
const browser = await launch();
const page = await browser.newPage();
await page.setViewport({ width: 1100, height: 900 });
await page.goto("http://localhost:8080/admin/", { waitUntil: "networkidle0" });
await page.type("#u", "owner"); await page.type("#pw", "owner-password-1"); await page.click("#loginBtn");
await page.waitForSelector("#panel .arow");
const sel = () => page.$eval('[role="tab"][aria-selected="true"]', t => t.dataset.tab);
const active = () => page.evaluate(() => document.activeElement.dataset.tab);
check("only the selected tab is in the tab order", await page.$$eval('[role="tab"]', t => t.filter(x => x.tabIndex === 0).length === 1 && t.find(x => x.tabIndex === 0).getAttribute("aria-selected") === "true"));
check("panel is labelled by the selected tab", await page.$eval("#panel", p => p.getAttribute("aria-labelledby") === "tab-stock"));
await page.focus('[data-tab="stock"]');
await page.keyboard.press("ArrowRight"); await new Promise(r => setTimeout(r, 500));
check("Right arrow selects the next tab and keeps focus on it", (await sel()) === "reorder" && (await active()) === "reorder");
await page.keyboard.press("End"); await new Promise(r => setTimeout(r, 500));
check("End goes to the last tab", (await sel()) === "account" && (await active()) === "account");
await page.keyboard.press("ArrowRight"); await new Promise(r => setTimeout(r, 500));
check("Right arrow wraps to the first", (await sel()) === "stock");
await page.keyboard.press("ArrowLeft"); await new Promise(r => setTimeout(r, 500));
check("Left arrow wraps to the last", (await sel()) === "account");
await page.keyboard.press("Home"); await new Promise(r => setTimeout(r, 500));
check("Home goes to the first", (await sel()) === "stock");
console.log(results.every(Boolean) ? "ALL PASS" : "SOME FAILED");
await browser.close();
